
baseURL = "https://brainplorer.com/"
languageCode = "en-us"
title = "Brainplorer"
theme = "ananke"
buildFuture = true
paginate = 12
enableRobotsTXT = true
buildFuture = false

[params]
  mainSections = ["posts"]
